language.Add("pug_ghost", 		"Ghosted entities have limited interactability")
language.Add("pug_entfrozen", 	"Target entity frozen")
language.Add("pug_tool2fast", 	"You are using your tool gun too fast, slow down!")
language.Add("pug_spawn2fast", 	"You are spawning stuff too fast, slow down!")
language.Add("pug_toolworld", 	"You may not use the tool gun on the world")
language.Add("pug_lagdetected", "Lag detected, running cleanup function!")
language.Add("pug_lagpanic", 	"Heavy lag detected, running panic function!")
language.Add("pug_lagsettings", "Your average tickrate does not match your set tickrate, please review your settings!")