local l = include("pug/bin/language.lua")

l.add("bone.manipulate.clamp", "Attempted to set ManipulateBoneScale to %d, clamping to %d.")
l.add("invalid.colour", "Invalid color passed to SetColor! This error prevents stuff from turning purple/pink.")
l.add("ghost.expose", "[PUG][ExposeGhoster] This error is generated by the `ExposeGhoster` setting in the `ghosting` module.")
l.add("ghost.noInit", "[PUG] PUGGhost was not initialized on Entity[%c][%s]")

return l
